// Generated by CoffeeScript 1.7.1
(function() {
  $('.question .vote-up-off, .question .vote-down-off').one('click', function(event) {
    var data, dataClass, jqXhr, options, tthis;
    event.preventDefault();
    tthis = $(this);
    dataClass = tthis.attr('data-class');
    data = {
      id: tthis.attr('data-id')
    };
    options = {
      url: tthis.attr('data-url'),
      data: data,
      type: 'POST',
      dataType: 'json',
      cache: false,
      beforeSend: function(xhr, setting) {
        return tthis.addClass(dataClass);
      }
    };
    jqXhr = $.ajax(options);
    jqXhr.done(function(data, textStatus, jqXHR) {
      if (data.errno) {
        alert(data.message);
        return tthis.removeClass(dataClass);
      } else {
        tthis.siblings('.vote-count').html(data.vote_score);
        return $('.question .vote-up-off, .question .vote-down-off').off('click');
      }
    });
    jqXhr.fail(function(xhr, textStatus, errorThrown) {
      return alert(textStatus);
    });
    return true;
  });

  $('.question .star-off').on('click', function(event) {
    var data, dataClass, jqXhr, options, tthis;
    event.preventDefault();
    tthis = $(this);
    dataClass = tthis.attr('data-class');
    data = {
      id: tthis.attr('data-id')
    };
    options = {
      url: tthis.attr('data-url'),
      data: data,
      type: 'POST',
      dataType: 'json',
      cache: false,
      beforeSend: function(xhr, setting) {
        if (tthis.hasClass(dataClass)) {
          return tthis.removeClass(dataClass);
        } else {
          return tthis.addClass(dataClass);
        }
      }
    };
    jqXhr = $.ajax(options);
    jqXhr.done(function(data, textStatus, jqXHR) {
      if (data.errno) {
        alert(data.message);
        if (tthis.hasClass(dataClass)) {
          return tthis.removeClass(dataClass);
        } else {
          return tthis.addClass(dataClass);
        }
      }
    });
    jqXhr.fail(function(xhr, textStatus, errorThrown) {
      return alert(textStatus);
    });
    return true;
  });

}).call(this);
