// Generated by CoffeeScript 1.7.1
(function() {
  $('.question .vote-up-off, .question .vote-down-off').one('click', function(event) {
    var data, jqXhr, options, tthis;
    event.preventDefault();
    tthis = $(this);
    data = {
      id: tthis.attr('data-id')
    };
    options = {
      url: tthis.attr('data-url'),
      data: data,
      type: 'POST',
      dataType: 'json',
      cache: false
    };
    jqXhr = $.ajax(options);
    jqXhr.done(function(data, textStatus, jqXHR) {
      if (data.errno) {
        return alert(data.message);
      } else {
        tthis.addClass(tthis.attr('data-class'));
        tthis.siblings('.vote-count').html(data.vote_score);
        return $('.question .vote-up-off, .question .vote-down-off').off('click');
      }
    });
    jqXhr.fail(function(xhr, textStatus, errorThrown) {
      return alert(textStatus);
    });
    return true;
  });

  $('.question .star-off').on('click', function(event) {
    var data, jqXhr, options, tthis;
    event.preventDefault();
    tthis = $(this);
    data = {
      id: tthis.attr('data-id')
    };
    options = {
      url: tthis.attr('data-url'),
      data: data,
      type: 'POST',
      dataType: 'json',
      cache: false
    };
    jqXhr = $.ajax(options);
    jqXhr.done(function(data, textStatus, jqXHR) {
      if (data.errno) {
        return alert(data.message);
      } else {
        if (data.action === 'insert') {
          return tthis.addClass(tthis.attr('data-class'));
        } else {
          return tthis.removeClass(tthis.attr('data-class'));
        }
      }
    });
    jqXhr.fail(function(xhr, textStatus, errorThrown) {
      return alert(textStatus);
    });
    return true;
  });

}).call(this);
